MvcCoreElasticCache/Models/Coche.cs
namespace MvcCoreElasticCache.Models
{
    public class Coche
    {
        public int IdCoche { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Imagen { get; set; }
    }
}

MvcCoreElasticCache/Models/ErrorViewModel.cs
namespace MvcCoreElasticCache.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreElasticCache/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreElasticCache.Models;
using MvcCoreElasticCache.Repositories;
using MvcCoreElasticCache.Services;

namespace MvcCoreElasticCache.Controllers
{
    public class CochesController : Controller
    {
        private RepositoryCoches repo;
        private ServiceAWSCache service;

        public CochesController(RepositoryCoches repo,
            ServiceAWSCache service)
        {
            this.repo = repo;
            this.service = service;
        }

        public IActionResult Index()
        {
            List<Coche> coches = this.repo.GetCoches();
            return View(coches);
        }

        public IActionResult Details(int id)
        {
            Coche coche = this.repo.GetCoche(id);
            return View(coche);
        }

        public async Task<IActionResult> Favoritos()
        {
            List<Coche> favoritos = await this.service.GetCochesFavoritosAsync();
            return View(favoritos);
        }

        public async Task<IActionResult> SeleccionFavorito(int idcoche)
        {
            // buscamos el coche dentro del xml
            Coche coche = this.repo.GetCoche(idcoche);
            await this.service.AddCocheFavoritoAsync(coche);
            return RedirectToAction("Favoritos");
        }

        public async Task<IActionResult> DeleteFavorito(int idcoche)
        {
            await this.service.ELiminarCocheFavoritoAsync(idcoche);

            return RedirectToAction("Favoritos");
        }
    }
}

MvcCoreElasticCache/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreElasticCache.Models;
using System.Diagnostics;

namespace MvcCoreElasticCache.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreElasticCache/Views/Coches/Details.cshtml
@model Coche

<ul class="list-group">
    <li class="list-group-item">
        <div class="">
            <img class="img-fluid" src="@Model.Imagen" alt="@Model.Marca" />
            <p class="py-3">@Model.Marca</p>
        </div>
        <div class="d-flex justify-content-between">
            <a asp-controller="Coches" asp-action="Index">
                Volver
            </a>
            <a asp-controller="Coches" asp-action="Eliminar" asp-route-id="@Model.IdCoche">
                Eliminar
            </a>
        </div>
    </li>
</ul>

MvcCoreElasticCache/Views/Coches/Favoritos.cshtml
@model List<Coche>

<div class="container-xl">
    @if (Model != null)
    {
        <ul class="list-group">
            @foreach (Coche ch in Model)
            {
                <li class="list-group-item">
                    <div class="d-flex flex-wrap">
                        <img src="@ch.Imagen" width="130px" height="130px" alt="@ch.Modelo" />
                        <h2 class="text-info">
                            @ch.Modelo - @ch.Marca
                        </h2>
                    </div>
                    <a asp-controller="Coches"
                       asp-action="DeleteFavorito"
                       asp-route-idcoche="@ch.IdCoche">
                        eliminar favorito
                    </a>
                </li>
            }
        </ul>
    }
</div>

MvcCoreElasticCache/Views/Coches/Index.cshtml
@model List<Coche>

<div class="container-xl">
    <ul class="list-group">
        @foreach (Coche ch in Model)
        {
            <li class="list-group-item mb-3">
                <div class="">
                    <img class="img-fluid" src="@ch.Imagen" alt="@ch.Marca" width="130px" height="130px" />
                    <p class="py-3">@ch.Marca</p>
                </div>
                <div class="d-flex justify-content-between">
                    <a asp-controller="Coches" asp-action="Details" asp-route-id="@ch.IdCoche">
                        Detalles
                    </a>
                    <a asp-controller="Coches"
                       asp-action="SeleccionFavorito"
                       asp-route-idcoche="@ch.IdCoche">
                        Añadir favorito
                    </a>
                </div>
            </li>
        }
    </ul>
</div>

MvcCoreElasticCache/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreElasticCache/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreElasticCache</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreElasticCache.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreElasticCache</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Coches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Favoritos">Favoritos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcCoreElasticCache - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>